### ISSUE TITLE
Weird huge row height when using cellspace on p-column type with empty cell

### ISSUE THREAD

**Issue by quark67** [JosselinNoirel/cellspace#3]
The code:

```tex
\documentclass[11pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{cellspace}
\begin{document}

\begin{tabular}{|c|S{p{1cm}}|}
    \hline
    foo &  \\
    \hline
     a & É \\
    \hline  
\end{tabular}

\end{document}
```

produce an white first page, and an huge height first row on the second page.

Bug also with `m` column-type (but not with `l`, `c` or `r` column type).

See also https://tex.stackexchange.com/questions/588370/weird-huge-row-height-when-using-cellspace-on-p-column-type-with-empty-cell

**Comment by JosselinNoirel** [comment]
Hi, thanks for reporting the bug. v1.9.0 solves the problem.
