### ISSUE TITLE
La commande \@endpbox a changé

### ISSUE THREAD

**Issue by petiard** [JosselinNoirel/cellspace#4]
Bonjour
Dans la nouvelle version de array.sty (2021/04/20), la commande \@endpbox a encore changé : elle est maintenant :
\def\@endpbox{\@finalstrut\@arstrutbox \par \color@endgroup \egroup\hfil}
(ligne 161 de array.sty)

alors qu'auparavant (après le 2018/12/30), elle était : 
\def\@endpbox{\@finalstrut \@arstrutbox \color@endgroup \egroup \hfil}

et, avent le 2018/12/30 : 
\def\@endpbox{\@finalstrut \@arstrutbox \egroup \hfil}

et alors, charger cellspace.sty occasionne le Warning : 
LaTeX Warning: Command \@endpbox  has changed.
               Check if current package is valid.

Cordialement

François Pétiard

**Comment by petiard** [comment]
Rebonjour

Le fichier joint semble fonctionner sans warning (voir les lignes 23 à 37).
J'ai été obligé de rajouter .txt comme extension sinon le fichier était refusé.

François Pétiard
[cellspace.sty.txt](https://github.com/JosselinNoirel/cellspace/files/6719822/cellspace.sty.txt)

**Comment by wgrundlingh** [comment]
This has been revisited here:
  https://chat.stackexchange.com/transcript/message/58682705#58682705
The suggestion to restore `\@endpbox` so it contains `\par` might be sufficient to resolve the problem.

**Comment by JosselinNoirel** [comment]
Thanks you for reporting the problem and sorry for the delay in handling it; this is now solved with v1.9.0.
