### ISSUE TITLE
conflict with package siunitx

### ISSUE THREAD

**Issue by thomaspreu** [JosselinNoirel/cellspace#5]
Using cellspace in a tabular when the package siunitx is loaded produces errors, at least for me. Here's a minimal (non)working example:

> \documentclass[a4paper,12pt]{article}
> %\usepackage{siunitx}
> \usepackage{cellspace}
> 
> \begin{document}
> 
> %\begin{tabular}{ll}
> \begin{tabular}{SlSl}
> (a) $(1,3,5,7)$ &
> (b) $\left(\frac{1}{3},\frac{1}{4},\frac{1}{5},\frac{1}{6}\right)$ \\
> (c) $\left(-1,1,-1,1\right)$ &
> (d) $\left(\frac{3}{2},\frac{7}{4},\frac{15}{8},\frac{31}{16}\right)$ 
> \end{tabular}
> 
> %\SI{1.0}{\newton}
> 
> \end{document}

This code compiles. If you unquote the second line it does not. If you unquote all three quoted lines and quote the line which starts the cellspace tabular it also compiles.

**Comment by petiard** [comment]
siunitx définit aussi le type de colonne S.
Solution : 
\usepackage[column=C]{cellspace} %voir la doc de cellspace page 4

puis :
\begin{tabular}{ClCl}

Vous pouvez évidemment remplacer C par O ou P ou ....
François
PS : une remarque : votre code ne compile pas, il manque un \ à la fin de la première ligne de votre tableau

**Comment by davidcarlisle** [comment]
Note `siunitx` has a similar option to use a different letter for its `S` column, so a `siunitx` option `table-column-type=Q` in the document preamble would also avoid clash on `S`.
